definitions:
  auth.LoginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  auth.ResponseResult:
    $ref: '#/definitions/handler.ResponseResult'
  handler.ResponseResult:
    properties:
      code:
        description: 状态码
        example: 100
        type: integer
      data:
        description: 数据
        type: object
      msg:
        description: 提示
        example: 密码错误
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录表单
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "100":
          description: Continue
          schema:
            $ref: '#/definitions/auth.ResponseResult'
        "104":
          schema:
            $ref: '#/definitions/auth.ResponseResult'
      summary: 根据用户名和密码登录
      tags:
      - Auth
swagger: "2.0"
